# Generated by Django 6.1.1 on 2026-09-28 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_content_action_button_text_and_more'),
        ('events', '0002_alter_event_options_event_city_slug_event_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='catalog.category'),
        ),
    ]
