# Generated by Django 6.1.1 on 2026-09-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merch',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='merch',
            name='badge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='merch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='merch',
            name='franchise',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merch',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merch',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='merch',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merch',
            name='sub_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='merch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='merch',
            name='category',
            field=models.CharField(choices=[('figures', 'Statues & Figures'), ('apparel', 'Streetwear & Apparel'), ('props', 'Prop Replicas')], default='figures', max_length=20),
        ),
        migrations.AlterField(
            model_name='merch',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='merch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='merch/images'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='merch',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='merch',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
