# Generated by Django 6.1.1 on 2026-09-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_alter_merch_options_merch_badge_merch_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='merch',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='merch',
            name='tags',
        ),
        migrations.AddField(
            model_name='merch',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='merch.merchtag'),
        ),
    ]
