# Generated by Django 6.1.1 on 2026-09-28 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_content_action_button_text_and_more'),
        ('merch', '0003_merchtag_remove_merch_stock_remove_merch_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='fandom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merch_items', to='catalog.category'),
        ),
    ]
