# Generated by Django 6.1.1 on 2026-09-28 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_content_action_button_text_and_more'),
        ('characters', '0002_alter_category_options_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='catalog.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
