# Generated by Django 6.1.1 on 2026-09-28 20:35

import django.db.models.deletion
from django.db import migrations, models


def copy_catalog_categories(apps, schema_editor):
    CharacterCategory = apps.get_model('characters', 'Category')
    CatalogCategory = apps.get_model('catalog', 'Category')
    CharacterProfile = apps.get_model('characters', 'CharacterProfile')
    mapping = {}
    for category in CatalogCategory.objects.all().order_by('pk'):
        copied, _ = CharacterCategory.objects.get_or_create(
            name=category.name,
            defaults={'slug': category.slug},
        )
        mapping[category.pk] = copied.pk
    for old_id, new_id in mapping.items():
        CharacterProfile.objects.filter(category_id=old_id).update(category_id=new_id)


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_characterprofile_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(copy_catalog_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='characterprofile',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='characters.category'),
        ),
    ]
