# Generated by Django 6.1.1 on 2026-09-28 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotquery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='chatbotfaq',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='chatbotfaq',
            name='keyword',
            field=models.CharField(help_text='Comma-separated words people might type, e.g. bookmark, save, favorite', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatbotquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatbotquery',
            name='matched_faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.chatbotfaq'),
        ),
        migrations.AlterField(
            model_name='chatbotquery',
            name='session_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='chatbotquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
