# Generated by Django 6.1.1 on 2026-09-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('VIEWED', 'Viewed'), ('BOOKMARKED', 'Bookmarked'), ('RATED', 'Rated'), ('LOGGED IN', 'Logged In'), ('SUBMITTED', 'Submitted'), ('FEEDBACK', 'Sent feedback')], max_length=10),
        ),
    ]
