# Generated by Django 6.1.1 on 2026-09-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='action_button_text',
            field=models.CharField(default='Stream', max_length=20),
        ),
        migrations.AddField(
            model_name='content',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='content',
            name='meta_label',
            field=models.CharField(blank=True, help_text="e.g., 'Ep 11 • TV-MA'", max_length=50),
        ),
    ]
