# Generated by Django 6.1.1 on 2026-09-28 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_content_action_button_text_content_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='action_button_text',
        ),
        migrations.RemoveField(
            model_name='content',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='content',
            name='meta_label',
        ),
    ]
