# Generated by Django 6.1.1 on 2026-09-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='severity',
            field=models.CharField(choices=[('low', 'Minor / Cosmetic'), ('medium', 'Normal / Functional'), ('high', 'Critical / Blocker')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('resolved', 'Resolved')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('query', 'Query'), ('content', 'Content Correction')], default='bug', max_length=20),
        ),
    ]
